spring.jpa.database: "postgresql"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
spring.datasource.platform: "postgresql"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/test"
spring.datasource.username: "postgres"
spring.datasource.password: "postgres"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
signing.key: "345345fsdfsf5345"
keystore.file: "config/mystore.jks"
keystore.password: "mypass"
keystore.keypair: "mykey"

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.jams: DEBUG
