spring.jpa.show-sql: "false"
#spring.jpa.database: "MySQL"
#spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.MySQL5Dialect"
#spring.datasource.platform: "mysql"
#spring.database.driverClassName: "com.mysql.jdbc.Driver"
#spring.datasource.url: "jdbc:mysql://localhost:3306/test"
#spring.datasource.username: "root"
#spring.datasource.password: ""
spring.jpa.database: "postgresql"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
spring.datasource.platform: "postgresql"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/test"
spring.datasource.username: "postgres"
spring.datasource.password: "postgres"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"
keystore.file: "config/mystore.jks"
keystore.password: "mypass"
keystore.keypair: "mykey"